config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:show]
  resources :genders, except: [:show]
  resources :titles, except: [:show]
  resources :colonies, except: [:show]
  resources :cities, except: [:show]
  resources :states, except: [:show]
  resources :entries, except: [:show]
  resources :permissions
  resources :areas, except: [:show]
  resources :roles
  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    # Redirect to the authenticated path if the user is authenticated.
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    # Redirect to the unauthenticated path if the user is unauthenticated.
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # List all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      # Allows to create an user
      get '/users/new', to: 'users/registrations#new', as: :new_user_registration
      post '/users', to: 'users/registrations#create', as: :create_user_registration

      # Allows to edit our own profile
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update', as: :update_profile, via: [:patch, :put]

      # Allows to edit the profile of an user.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user_registration
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user_registration, via: [:patch, :put]

      # Allows to modify our own password.
      get '/users/change_password', to: 'users/registrations#change_password', as: :change_password
      match '/save_password', to: 'users/registrations#save_password', as: :save_password, via: [:patch, :put]

      # Allows to edit the passwords of other users.
      get '/users/:id/change_password', to: 'users/registrations#change_user_password', as: :change_user_password
      match '/save_password/:id', to: 'users/registrations#save_user_password', as: :save_user_password,
            via: [:patch, :put]

      # Displays the information of a user.
      get '/users/:id', to: 'users/registrations#show', as: :user_registration

      # Allows to delete a user.
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Routes for the different types of requests
      get '/requests/new/project', to: 'requests#new_project', as: :new_project
      get '/requests/new/complaint', to: 'requests#new_complaint', as: :new_complaint
      get '/requests/new/audience', to: 'requests#new_audience', as: :new_audience
      get '/requests/new/resume', to: 'requests#new_resume', as: :new_resume
      get '/requests/new/management', to: 'requests#new_management', as: :new_management

      get '/project_requests', to: 'requests#index_projects', as: :index_projects
      get '/project_complaints', to: 'requests#index_complaints', as: :index_complaints
      get '/project_audiences', to: 'requests#index_audiences', as: :index_audiences
      get '/project_resumes', to: 'requests#index_resumes', as: :index_resumes
      get '/project_managements', to: 'requests#index_managements', as: :index_managements

      post '/requests/generate_request_pdf/:id', to: 'requests#generate_request_pdf', as: :generate_request_pdf

      # Generate the seed for the States, Cities, and Colonies based on an excel file.
      post '/application/importation', to: 'application#importation', as: :importation

      # Get a list of actions that a controller has.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Generate the seeds of the permissions and its relations with roles
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays the selected rol with his permissions
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Makes the relations of a role with the permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      resources :requests, except: [:new]
    end

    # Allows the execution of the back button in the login options.
    get '/login', to: 'devise/seasons#new'
  end
end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id             :integer          not null, primary key
#  folio          :string
#  reception_date :date
#  data_type      :integer
#  user_id        :integer
#  entry_id       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  area_id        :integer
#  responsible_id :integer
#

class Request < ActiveRecord::Base
  has_one :project, dependent: :destroy
  has_one :complaint, dependent: :destroy
  has_one :audience, dependent: :destroy
  has_one :resume, dependent: :destroy
  has_one :management, dependent: :destroy
  has_one :contact, dependent: :destroy
  has_one :general_information, dependent: :destroy

  has_many :request_files, dependent: :destroy

  belongs_to :user
  belongs_to :area
  belongs_to :responsible, foreign_key: :responsible_id, class_name: 'User'
  belongs_to :entry

  enum data_type: [:project, :complaint, :audience, :resume, :management]

  validates_presence_of :reception_date, :data_type, :entry_id

  accepts_nested_attributes_for :project
  accepts_nested_attributes_for :complaint
  accepts_nested_attributes_for :audience
  accepts_nested_attributes_for :resume
  accepts_nested_attributes_for :management
  accepts_nested_attributes_for :contact
  accepts_nested_attributes_for :general_information
  accepts_nested_attributes_for :request_files, allow_destroy: true, reject_if: :all_blank

  def self.i18n_data_type(hash = {})
    data_types.keys.each { |key| hash[I18n.t("data_types.#{key}")] = key }
    hash
  end

  def set_folio
    folio_name = ''

    case
      when self.project
        folio_name = 'PRO-'
      when self.complaint
        folio_name = 'DEN-'
      when self.audience
        folio_name = 'AUD-'
      when self.resume
        folio_name = 'CUR-'
    end

    self.update_attributes(folio: "#{folio_name}#{self.id}")
  end

  def assign_json_attributes(params)
    attributes = params[:request][:resume_attributes].slice(:work_objective, :experience)
    self.resume.work_objective = attributes[:work_objective]
    self.resume.experience = attributes[:experience]
    self.resume.profile = attributes
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :generate_request_pdf]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all.paginate(page: params[:page], per_page: 15)
  end

  def index_projects
    @requests = Request.project.paginate(page: params[:page], per_page: 15)

    render 'index'
  end

  def index_complaints
    @requests = Request.complaint.paginate(page: params[:page], per_page: 15)

    render 'index'
  end

  def index_audiences
    @requests = Request.audience.paginate(page: params[:page], per_page: 15)

    render 'index'
  end

  def index_resumes
    @requests = Request.resume.paginate(page: params[:page], per_page: 15)

    render 'index'
  end

  def index_managements
    @requests = Request.management.paginate(page: params[:page], per_page: 15)

    render 'index'
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  # def new
  #   @request = Request.new
  # end

  def new_project
    @request = Request.new(data_type: :project)
    @request.build_contact
    @request.build_project
    @request.build_general_information

    render 'new'
  end

  def new_complaint
    @request = Request.new(data_type: :complaint)
    @request.build_contact
    @request.build_complaint
    @request.build_general_information

    render 'new'
  end

  def new_audience
    @request = Request.new(data_type: :audience)
    @request.build_contact
    @request.build_audience
    @request.build_general_information

    render 'new'
  end

  def new_resume
    @request = Request.new(data_type: :resume)
    @request.build_contact
    @request.build_resume
    @request.build_general_information

    render 'new'
  end

  def new_management
    @request = Request.new(data_type: :management)
    @request.build_contact
    @request.build_management
    @request.build_general_information

    render 'new'
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    @request.assign_json_attributes(params) if @request.resume?

    respond_to do |format|
      if @request.save
        @request.set_folio
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    @request.assign_json_attributes(params) if @request.resume?
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_request_pdf
    pdf_name = current_user.email + '_' + Time.now.strftime('%Y%d%m_%H%M%S') + '.pdf'
    html = render_to_string(action: :generate_pdf, layout: false)
    pdf = WickedPdf.new.pdf_from_string(html)

    send_data(pdf,
              filename: pdf_name,
              disposition: 'attachment')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit(:reception_date, :data_type, :user_id, :entry_id, :area_id, :responsible_id,
                                    project_attributes: [:id, :category_id, :name, :description],
                                    general_information_attributes: [:id, :request_id, :title_id, :name, :father_last_name,
                                                                     :mother_last_name, :birthdate, :gender_id, :email,
                                                                     :position, :organization, :ip, :anonymous,
                                                                     contact_phones_attributes: [:id, :tag, :number, :_destroy]],
                                    contact_attributes: [:id, :request_id, :state_id, :city_id, :colony_id, :postcode,
                                                         :street, :internal_number, :external_number],
                                    complaint_attributes: [:id, :category_id, :subject, :notes],
                                    audience_attributes: [:id, :category_id, :subject, :description],
                                    management_attributes: [:id, :category_id, :subject, :description],
                                    resume_attributes: [:id, :category_id,
                                                        studies_attributes: [:id, :institution, :degree, :end_study, :_destroy],
                                                        abilities_attributes: [:id, :name, :_destroy],
                                                        languages_attributes: [:id, :name, :percentage, :_destroy]],

                                    request_files_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_audience_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('.title') %></h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <div class="box-body">
    <div class="form-group">
      <%= f.label :category_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select(:category_id, Category.audience, :id, :name, {prompt: t('helpers.select.prompt')},
                              {class: 'form-control col-md-12'}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :subject, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :subject, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
  </div>
</div>

app/views/requests/_complaint_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('.title') %></h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <div class="box-body">
    <div class="form-group">
      <%= f.label :category_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select(:category_id, Category.complaint, :id, :name, {prompt: t('helpers.select.prompt')},
                              {class: 'form-control col-md-12'}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :subject, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :subject, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :notes, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :notes, class: 'form-control' %>
      </div>
    </div>
  </div>
</div>

app/views/requests/_contact_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('.title') %></h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <div class="box-body">
    <div class="form-group">
      <%= f.label :state_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select(:state_id, State.all, :id, :name, {prompt: t('helpers.select.prompt')},
                              {class: 'form-control col-md-12'}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select(:city_id, City.all, :id, :name, {prompt: t('helpers.select.prompt')},
                              {class: 'form-control col-md-12'}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :colony_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select(:colony_id, Colony.all, :id, :name, {prompt: t('helpers.select.prompt')},
                              {class: 'form-control col-md-12'}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :postcode, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :postcode, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :street, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :street, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :internal_number, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :internal_number, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :external_number, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :external_number, class: 'form-control' %>
      </div>
    </div>
  </div>
</div>

app/views/requests/_file_form.html.erb
<div class="nested-fields col-md-12">
  <div class="group-form row">
    <div class="col-md-10 no-padding-right">
      <%= f.file_field :file, class: 'form-control' %>
    </div>
    <div class="col-md-2">
      <div class="inline-flex">
        <%= link_to_remove_association '<i class="fa fa-times"></i>'.html_safe, f, class: 'btn btn-flat btn-default' %>
      </div>
    </div>
  </div>
  <br/>
</div>

app/views/requests/_form.html.erb
<div class="box box-primary" id="request">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('.title') %></h3>
    <% if request.complaint? %>
        <% if request.general_information.anonymous %>
            <div class="pull-right box-tools">
              <a href="javascript:;" class="btn btn-flat btn-info anonymous-btt" data-toggle="tooltip" title="Solo los campos necesarios permanecerán obligatorios.">
                Anónimo </a>
            </div>
        <% else %>
            <div class="pull-right box-tools">
              <a href="javascript:;" class="btn btn-flat btn-default anonymous-btt" data-toggle="tooltip" title="Solo los campos necesarios permanecerán obligatorios.">
                Anónimo </a>
            </div>
        <% end %>
    <% end %>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <%= form_for(request, html: {class: 'form-horizontal'}, validate: true) do |f| %>
      <div class="box-body">
        <% unless request.new_record? %>
            <div class="form-group">
              <%= f.label :folio, class: 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.text_field :folio, value: (request.folio), class: 'form-control', readonly: true %>
              </div>
            </div>
        <% end %>
        <div class="form-group">
          <%= f.label :reception_date, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :reception_date, value: (l request.reception_date, format: :custom), class: 'form-control date-picker-form', validate: false %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :area_id, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.collection_select(:area_id, Area.all, :id, :name, {prompt: t('helpers.select.prompt')},
                                    {class: 'form-control col-md-12'}) %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :responsible_id, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.collection_select(:responsible_id, User.all, :id, :full_name, {prompt: t('helpers.select.prompt')},
                                    {class: 'form-control col-md-12'}) %>
          </div>
        </div>

        <%= f.hidden_field :data_type %>

        <div class="form-group">
          <%= f.label :entry_id, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.collection_select(:entry_id, Entry.all, :id, :name, {prompt: t('helpers.select.prompt')},
                                    {class: 'form-control col-md-12'}) %>
          </div>
        </div>
      </div>

      <% case %>
  <% when request.project? %>
          <%= f.fields_for :project, request.project do |project| %>
              <%= render 'project_form', f: project %>
          <% end %>
      <% when request.complaint? %>
          <%= f.fields_for :complaint, request.complaint do |complaint| %>
              <%= render 'complaint_form', f: complaint %>
          <% end %>
      <% when request.audience? %>
          <%= f.fields_for :audience, request.audience do |audience| %>
              <%= render 'audience_form', f: audience %>
          <% end %>
      <% when request.resume? %>
          <%= f.fields_for :resume, request.resume do |resume| %>
              <%= render 'resume_form', f: resume, request: @request  %>
          <% end %>
      <% when request.management? %>
          <%= f.fields_for :management, request.management do |management| %>
              <%= render 'management_form', f: management %>
          <% end %>
      <% end %>

      <%= render 'request_files', f: f, request: request %>

      <%= f.fields_for :general_information, request.general_information do |general_information| %>
          <%= render 'general_information_form', f: general_information, request: request %>
      <% end %>

      <%= f.fields_for :contact, request.contact do |contact| %>
          <%= render 'contact_form', f: contact %>
      <% end %>

      <!-- /.box-body -->
      <div class="box-footer">
        <div class="col-sm-offset-2">
          <%= f.button t('helpers.create'), class: 'btn btn-flat btn-success' %>
          <%= link_to t('helpers.cancel'), requests_path, class: 'btn btn-flat btn-danger' %>
        </div>
      </div>
  <% end %>
</div>

app/views/requests/_language_fields.html.erb
<div class="nested-fields col-md-12">
  <div class="group-form row">
    <div class="col-md-7 no-padding-right">
      <%= f.text_field :name, class: 'form-control phone-mask', placeholder: t('.language') %>
    </div>
    <div class="col-md-5">
      <div class="inline-flex">
        <%= f.text_field :percentage, class: 'form-control extension-mask', placeholder: t('.percentage'),
                         type: 'number', min: '0', max:'100' %>
        <%= link_to_remove_association '<i class="fa fa-times"></i>'.html_safe, f, class: 'btn btn-flat btn-default',
                                       title: t('.destroy') %>
      </div>
    </div>
  </div>
  <br/>
</div>

app/views/requests/_project_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('.title')%></h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <div class="box-body">
    <div class="form-group">
      <%= f.label :category_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select(:category_id, Category.project, :id, :name, {prompt: t('helpers.select.prompt')},
                              {class: 'form-control col-md-12'}) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
  </div>
</div>

app/views/requests/_request_files.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('requests.file_form.title') %></h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <div class="box-body">
    <div class="form-group no-margin-bottom">
      <label class="col-md-2 control-label"><%= t 'requests.file_form.name' %></label>

      <div class="col-md-10">
        <div>
          <%= f.fields_for :request_files, request.request_files do |file| %>
              <%= render 'file_form', f: file %>
          <% end %>
        </div>

        <div class="form-group">
          <div id="add-phone" class="links col-md-12">
            <%= link_to_add_association "<i class='fa fa-plus'></i> #{t '.add'}".html_safe, f, :request_files,
                                        class: 'form-control', partial: 'file_form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/requests/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Editar solicitud</h1>
  </section>
  <section class="content">
    <%= render 'form', request: @request %>
  </section>
</div>

app/views/requests/generate_pdf.html.erb
<%= stylesheet_link_tag(asset_data_base64('application.css')) %>

<head>
  <meta charset='utf-8' />
</head>

<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Solicitud</h1>
  </section>
  <section class="content">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Solicitud</h3>
        <div class="box-tools">
        </div>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <%= form_for(@request, html: {class: 'form-horizontal'}) do |f| %>
          <div class="box-body">
            <div class="form-group">
              <%= label :folio, 'Folio', {class: 'col-sm-2 control-label'} %>
              <div class="col-sm-10">
                <div class="form-control col-md-12">
                  <%= @request.folio%>
                </div>
              </div>
            </div>
            <div class="form-group">
              <%= label :reception_date, 'Fecha de recepción', {class: 'col-sm-2 control-label'} %>
              <div class="col-sm-10">
                <div class="form-control col-md-12">
                  <%= l @request.reception_date, format: :custom %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :area_id, class: 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.collection_select(:area_id, Area.all, :id, :name, {prompt: t('helpers.select.prompt')},
                                        {class: 'form-control col-md-12'}) %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :responsible_id, class: 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.collection_select(:responsible_id, User.all, :id, :full_name, {prompt: t('helpers.select.prompt')},
                                        {class: 'form-control col-md-12'}) %>
              </div>
            </div>

            <%= f.hidden_field :data_type %>

            <div class="form-group">
              <%= f.label :entry_id, class: 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.collection_select(:entry_id, Entry.all, :id, :name, {prompt: t('helpers.select.prompt')},
                                        {class: 'form-control col-md-12'}) %>
              </div>
            </div>
          </div>

          <% case %>
      <% when @request.project? %>
              <%= f.fields_for :project, @request.project do |project| %>
                  <%= render 'project_form', f: project %>
              <% end %>
          <% when @request.complaint? %>
              <%= f.fields_for :complaint, @request.complaint do |complaint| %>
                  <%= render 'complaint_form', f: complaint %>
              <% end %>
          <% when @request.audience? %>
              <%= f.fields_for :audience, @request.audience do |audience| %>
                  <%= render 'audience_form', f: audience %>
              <% end %>
          <% when @request.resume? %>
              <%= f.fields_for :resume, @request.resume do |resume| %>
                  <%= render 'resume_form', f: resume, request: @request   %>
              <% end %>
          <% end %>

          <%= render 'request_files', f: f, request: @request %>

          <%= f.fields_for :general_information, @request.general_information do |general_information| %>
              <%= render 'general_information_form', f: general_information %>
          <% end %>

          <%= f.fields_for :contact, @request.contact do |contact| %>
              <%= render 'contact_form', f: contact %>
          <% end %>

          <!-- /.box-body -->
          <div class="box-footer">
            <div class="col-sm-offset-2">
              <%= link_to 'Regresar', requests_path, class: 'btn btn-danger' %>
            </div>
          </div>
      <% end %>
    </div>
  </section>
</div>

app/views/requests/index.html.erb
<section class="content-header">
  <h1>Listado de Solicitudes</h1>
</section>
<section class="content">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">
        <%#= link_to '<i class="fa fa-plus"></i>'.html_safe, new_request_path, class: 'btn btn-flat bg-green' %>
      </h3>
      <div class="box-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Folio</th>
          <th>Fecha de Recepción</th>
          <th>Capturista</th>
          <th>Entrada</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @requests.each do |request| %>
            <tr>
              <td><%= request.folio %></td>
              <td><%= l request.reception_date, format: :custom %></td>
              <td><%= request.user.full_name %></td>
              <td><%= request.entry.name %></td>
              <td class="actions">
                <div>
                  <%= link_to '<i class="fa fa-search"></i>'.html_safe, request, class: 'btn btn-flat btn-xs bg-green' %>
                  <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_request_path(request), class: 'btn btn-flat btn-xs bg-blue' %>
                  <%= link_to '<i class="fa fa-trash"></i>'.html_safe, request, method: :delete,
                              data: {confirm: 'Are you sure?'}, class: 'btn btn-flat btn-xs bg-red' %>
                  <%= link_to '<i class="fa fa-file-pdf-o"></i>'.html_safe, generate_request_pdf_path(request), method: :post, class: 'btn btn-flat btn-xs bg-purple' %>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
      <%= custom_paginator @requests, 'no-margin pull-right' %>
    </div>
  </div>
</section>

app/views/requests/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Nueva solicitud</h1>
  </section>
  <section class="content">
    <%= render 'form', request: @request %>
  </section>
</div>