config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:show]
  resources :genders, except: [:show]
  resources :titles, except: [:show]
  resources :colonies, except: [:show]
  resources :cities, except: [:show]
  resources :states, except: [:show]
  resources :entries, except: [:show]
  resources :permissions
  resources :areas, except: [:show]
  resources :roles
  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    # Redirect to the authenticated path if the user is authenticated.
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    # Redirect to the unauthenticated path if the user is unauthenticated.
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # List all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      # Allows to create an user
      get '/users/new', to: 'users/registrations#new', as: :new_user_registration
      post '/users', to: 'users/registrations#create', as: :create_user_registration

      # Allows to edit our own profile
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update', as: :update_profile, via: [:patch, :put]

      # Allows to edit the profile of an user.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user_registration
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user_registration, via: [:patch, :put]

      # Allows to modify our own password.
      get '/users/change_password', to: 'users/registrations#change_password', as: :change_password
      match '/save_password', to: 'users/registrations#save_password', as: :save_password, via: [:patch, :put]

      # Allows to edit the passwords of other users.
      get '/users/:id/change_password', to: 'users/registrations#change_user_password', as: :change_user_password
      match '/save_password/:id', to: 'users/registrations#save_user_password', as: :save_user_password,
            via: [:patch, :put]

      # Displays the information of a user.
      get '/users/:id', to: 'users/registrations#show', as: :user_registration

      # Allows to delete a user.
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Routes for the different types of requests
      get '/requests/new/project', to: 'requests#new_project', as: :new_project
      get '/requests/new/complaint', to: 'requests#new_complaint', as: :new_complaint
      get '/requests/new/audience', to: 'requests#new_audience', as: :new_audience
      get '/requests/new/resume', to: 'requests#new_resume', as: :new_resume
      get '/requests/new/management', to: 'requests#new_management', as: :new_management

      get '/project_requests', to: 'requests#index_projects', as: :index_projects
      get '/project_complaints', to: 'requests#index_complaints', as: :index_complaints
      get '/project_audiences', to: 'requests#index_audiences', as: :index_audiences
      get '/project_resumes', to: 'requests#index_resumes', as: :index_resumes
      get '/project_managements', to: 'requests#index_managements', as: :index_managements

      post '/requests/generate_request_pdf/:id', to: 'requests#generate_request_pdf', as: :generate_request_pdf

      # Generate the seed for the States, Cities, and Colonies based on an excel file.
      post '/application/importation', to: 'application#importation', as: :importation

      # Get a list of actions that a controller has.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Generate the seeds of the permissions and its relations with roles
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays the selected rol with his permissions
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Makes the relations of a role with the permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      resources :requests, except: [:new]
    end

    # Allows the execution of the back button in the login options.
    get '/login', to: 'devise/seasons#new'
  end
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id          :integer          not null, primary key
#  name        :string
#  key         :string
#  description :text
#  scope       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Role < ActiveRecord::Base
  has_many :users
  has_many :permission_role, dependent: :destroy
  has_many :permissions, through: :permission_role

  enum scope: [:total, :site, :owner]

  validates_presence_of :name, :description, :scope
  validates_uniqueness_of :key, allow_blank: true

  def is_protected?
    self.key == 'god'
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all.paginate(page: params[:page], per_page: 15).order('id DESC')
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_url, notice: t('notifications_masc.success.resource.created',
                                                       resource: t('roles.form.resource')) }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(update_role_params)
        format.html { redirect_to roles_url, notice: t('notifications_masc.success.resource.updated',
                                                       resource: t('roles.form.resource')) }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: t('notifications_masc.success.resource.destroyed',
                                                     resource: t('roles.form.resource'))  }
      format.json { head :no_content }
    end
  end

  # Return the role that has been selected with the existing permissions
  def role_permissions
    @role = Role.find(params[:role_id])
    @permissions = Permission.order('controller').group_by { |t| t.controller }
  end

  # Create the relation between the the role and the permissions selected and writes them into the database
  def assign_permissions
    @role = Role.find params[:role_id]
    @role.permissions.delete_all
    if params[:permissions_ids].respond_to? 'each'
      params[:permissions_ids].each do |permission|
        PermissionRole.create(role_id: @role.id, permission_id: permission[1])
      end
    end

    respond_to do |format|
      format.html { redirect_to roles_url, notice: t('notifications_masc.info.permissions_assigned') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :description, :key, :scope, permission_ids: [])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def update_role_params
    params.require(:role).permit(:name, :description, :scope, permission_ids: [])
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Role</h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <%= form_for(@role, html: {class: 'form-horizontal'}, validate: true) do |f| %>
      <div class="box-body">
        <div class="form-group">
          <%= f.label :name, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: 'form-control', autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :key, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :key, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :description, class: 'form-control' %>
          </div>
        </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="col-sm-offset-2">
          <%= f.button 'Crear', class: 'btn btn-flat btn-success' %>
          <%= link_to 'Cancelar', roles_path, class: 'btn btn-flat btn-danger' %>
        </div>
      </div>
  <% end %>
</div>

app/views/roles/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Editar rol</h1>
  </section>
  <section class="content">
    <%= render 'form' %>
  </section>
</div>

app/views/roles/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <section class="content-header">
    <h1>Listado de Roles</h1>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">
          <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_role_path, class: 'btn btn-flat bg-green' %>
        </h3>
        <div class="box-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
            <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Name</th>
            <th>Key</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @roles.each do |role| %>
              <tr>
                <td><%= role.name %></td>
                <td><%= role.key %></td>
                <td><%= role.description %></td>
                <td class="actions">
                  <div>
                    <%= link_to '<i class="fa fa-search"></i>'.html_safe, role, class: 'btn btn-flat btn-xs bg-green' %>
                    <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_role_path(role), class: 'btn btn-flat btn-xs bg-blue' %>
                    <%= link_to '<i class="fa fa-exchange"></i>'.html_safe, role_permissions_url(role.id), class: 'btn btn-flat btn-xs bg-orange' %>
                    <%= link_to '<i class="fa fa-trash"></i>'.html_safe, role, method: :delete,
                                data: {confirm: 'Are you sure?'}, class: 'btn btn-flat btn-xs bg-red' %>
                  </div>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
      <div class="box-footer clearfix">
        <%= custom_paginator @roles, 'no-margin pull-right' %>
      </div>
    </div>
  </section>
</div>

app/views/roles/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Creación de rol</h1>
  </section>
  <section class="content">
    <%= render 'form' %>
  </section>
</div>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @role.key %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>