config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:show]
  resources :genders, except: [:show]
  resources :titles, except: [:show]
  resources :colonies, except: [:show]
  resources :cities, except: [:show]
  resources :states, except: [:show]
  resources :entries, except: [:show]
  resources :permissions
  resources :areas, except: [:show]
  resources :roles
  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    # Redirect to the authenticated path if the user is authenticated.
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    # Redirect to the unauthenticated path if the user is unauthenticated.
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # List all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      # Allows to create an user
      get '/users/new', to: 'users/registrations#new', as: :new_user_registration
      post '/users', to: 'users/registrations#create', as: :create_user_registration

      # Allows to edit our own profile
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update', as: :update_profile, via: [:patch, :put]

      # Allows to edit the profile of an user.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user_registration
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user_registration, via: [:patch, :put]

      # Allows to modify our own password.
      get '/users/change_password', to: 'users/registrations#change_password', as: :change_password
      match '/save_password', to: 'users/registrations#save_password', as: :save_password, via: [:patch, :put]

      # Allows to edit the passwords of other users.
      get '/users/:id/change_password', to: 'users/registrations#change_user_password', as: :change_user_password
      match '/save_password/:id', to: 'users/registrations#save_user_password', as: :save_user_password,
            via: [:patch, :put]

      # Displays the information of a user.
      get '/users/:id', to: 'users/registrations#show', as: :user_registration

      # Allows to delete a user.
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Routes for the different types of requests
      get '/requests/new/project', to: 'requests#new_project', as: :new_project
      get '/requests/new/complaint', to: 'requests#new_complaint', as: :new_complaint
      get '/requests/new/audience', to: 'requests#new_audience', as: :new_audience
      get '/requests/new/resume', to: 'requests#new_resume', as: :new_resume
      get '/requests/new/management', to: 'requests#new_management', as: :new_management

      get '/project_requests', to: 'requests#index_projects', as: :index_projects
      get '/project_complaints', to: 'requests#index_complaints', as: :index_complaints
      get '/project_audiences', to: 'requests#index_audiences', as: :index_audiences
      get '/project_resumes', to: 'requests#index_resumes', as: :index_resumes
      get '/project_managements', to: 'requests#index_managements', as: :index_managements

      post '/requests/generate_request_pdf/:id', to: 'requests#generate_request_pdf', as: :generate_request_pdf

      # Generate the seed for the States, Cities, and Colonies based on an excel file.
      post '/application/importation', to: 'application#importation', as: :importation

      # Get a list of actions that a controller has.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Generate the seeds of the permissions and its relations with roles
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays the selected rol with his permissions
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Makes the relations of a role with the permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      resources :requests, except: [:new]
    end

    # Allows the execution of the back button in the login options.
    get '/login', to: 'devise/seasons#new'
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  data_type  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :projects
  has_many :complaints
  has_many :audiences
  has_many :resumes

  enum data_type: [:project, :complaint, :audience, :resume, :management]

  validates_presence_of :name, :data_type

  def self.i18n_data_type(hash = {})
    data_types.keys.each { |key| hash[I18n.t("data_types.#{key}")] = key }
    hash
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 15)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @category.can_destroy?
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to categories_url, notice: 'The category was not destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :data_type)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Categoría</h3>
    <div class="box-tools">
    </div>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <%= form_for(category, html: {class: 'form-horizontal'}, validate: true) do |f| %>
      <div class="box-body">
        <div class="form-group">
          <%= f.label :name, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: 'form-control', autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :data_type, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.select :data_type, Category.i18n_data_type, {}, {class: 'form-control'} %>
          </div>
        </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="col-sm-offset-2">
          <%= f.button 'Crear', class: 'btn btn-flat btn-success' %>
          <%= link_to 'Cancelar', categories_path, class: 'btn btn-flat btn-danger' %>
        </div>
      </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Editar categoría</h1>
  </section>
  <section class="content">
    <%= render 'form' , category: @category %>
  </section>
</div>

app/views/categories/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <section class="content-header">
    <h1>Listado de Categorías</h1>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">
          <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_category_path, class: 'btn btn-flat bg-green' %>
        </h3>
        <div class="box-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
            <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Acciones</th>
          </tr>
          </thead>
          <tbody>
          <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.data_type %></td>
                <td class="actions">
                  <div>
                    <%= link_to '<i class="fa fa-search"></i>'.html_safe, category, class: 'btn btn-flat btn-xs bg-green' %>
                    <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_category_path(category), class: 'btn btn-flat btn-xs bg-blue' %>
                    <%= link_to '<i class="fa fa-trash"></i>'.html_safe, category, method: :delete,
                                data: {confirm: 'Are you sure?'}, class: 'btn btn-flat btn-xs bg-red' %>
                  </div>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
      <div class="box-footer clearfix">
        <%= custom_paginator @categories, 'no-margin pull-right' %>
      </div>
    </div>
  </section>
</div>

app/views/categories/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <section class="content-header">
    <h1>Nueva categoría</h1>
  </section>
  <section class="content">
    <%= render 'form' , category: @category %>
  </section>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @category.data_type %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>